<?php

// WARNING: DO NOT EDIT THIS FILE.
// This file is automatically generated by the Zoom Indexer application
// and will be updated each time you re-index your site. You should make all
// setting changes directly from the Indexer, via the Configuration window.
// 
// If you wish to modify the text messages such as "Search results for...",
// etc. then look up "Zoom Language Files" or "Translating the search page"
// in the Users Guide for information.

$UseUTF8 = 0;
$Charset = "iso-8859-1";
$Codepage = 28591;
$UseStemming = 1;
$StemmingAlgo = 2;
$NoCharset = 0;
$MapAccents = 1;
$AccentChars = array("á", "à", "â", "ã", "à", "Á", "À", "Â", "Ã", "À", "ç", "Ç", "ð", "é", "è", "ê", "É", "È", "Ê", "í", "ì", "î", "Í", "Ì", "Î", "ó", "ò", "ô", "Ó", "Ò", "Ô", "ú", "ù", "û", "Ú", "Ù", "Û", "ý", "Ý", "ä", "Ä", "ë", "Ë", "ï", "Ï", "ö", "Ö", "ü", "Ü", "ÿ", "å", "Å", "ø", "Ø", "æ", "Æ", "ß");
$NormalChars = array("a", "a", "a", "a", "a", "A", "A", "A", "A", "A", "c", "C", "d", "e", "e", "e", "E", "E", "E", "i", "i", "i", "I", "I", "I", "o", "o", "o", "O", "O", "O", "u", "u", "u", "U", "U", "U", "y", "Y", "a", "A", "e", "E", "i", "I", "o", "O", "u", "U", "y", "aa", "Aa", "oe", "Oe", "ae", "AE", "ss");
$MinWordLen = 2;
$Highlighting = 1;
$GotoHighlight = 0;
$PdfHighlight = 1;
$FormFormat = 2;
$Logging = 0;
$LogFileName = "./logs/searchwords.log";
$MaxKeyWordLineLen = 256;
$OutputBasewordBufferSize = 42837;
$OutputVariantBufferSize = 54377;
$DictIDLen = 4;
$NumKeywords = 5351;
$NumVariants = 5607;
$NumPages = 137;
$PageInfoSize = 2329;
$MaxMatches = 10000;
$MaxContextSeeks = 5000;
$MaxSearchTime = 120;
$DictReservedLimit = 165;
$DictReservedSuffixes = 83;
$DictReservedPrefixes = 124;
$DictReservedNoSpaces = 165;
$WordSplit = 1;
$ZoomInfo = 0;
$Timing = 1;
$DefaultToAnd = 1;
$SearchAsSubstring = 0;
$ToLowerSearchWords = 1;
$StripDiacritics = 0;
$ContextSize = 128;
$MaxContextKeywords = 3;
$WeightProximity = 0;
$AllowExactPhrase = 1;
$UseLinkTarget = 0;
$UseDateTime = 0;
$UseZoomImage = 0;
$WordJoinChars = ".-_'";
$Spelling = 1;
$SpellingWhenLessThan = 3;
$NumSpellings = 2577;
$Recommended = 0;
$NumRecommended = 0;
$RecommendedMax = 0;
$UseCats = 0;
$UseMetaFields = 0;
$NumMetaFields = 0;
$DisplayMetaFields = 0;
$TruncateShowURL = 0;
$DisplayNumber = 1;
$DisplayTitle = 1;
$DisplayMetaDesc = 0;
$DisplayContext = 1;
$DisplayTerms = 1;
$DisplayScore = 1;
$DisplayURL = 0;
$DisplayDate = 1;
$DisplayFilesize = 1;
$StartPtFailed = 0;
$Version = "Version 6.0 (1029) ENT";
$STR_FORM_SEARCHFOR = "Buscar:";
$STR_FORM_SUBMIT_BUTTON = "Enviar";
$STR_FORM_RESULTS_PER_PAGE = "Resultados por página:";
$STR_FORM_CATEGORY = "Categoría:";
$STR_FORM_CATEGORY_ALL = "Todas";
$STR_FORM_MATCH = "mostrar resultados que contengan";
$STR_FORM_ANY_SEARCH_WORDS = "cualquier palabra";
$STR_FORM_ALL_SEARCH_WORDS = "todas las palabras";
$STR_NO_QUERY = "No introdujo cadena de búsqueda.";
$STR_RESULTS_FOR = "Resultados de la búsqueda:";
$STR_RESULTS_IN_ALL_CATEGORIES = "en todas las categorías";
$STR_RESULTS_IN_CATEGORY = "en la categoría";
$STR_POWEREDBY = "Powered by";
$STR_NO_RESULTS = "No hubo resultados";
$STR_RESULT = "resultado";
$STR_RESULTS = "resultados";
$STR_PHRASE_CONTAINS_COMMON_WORDS = "La siguiente frase contiene términos demasiado habituales, por lo que la búsqueda es limitada. Por favor refine su búsqueda";
$STR_SKIPPED_FOLLOWING_WORDS = "La(s) siguiente(s) palabra(s) han sido ignoradas por estar en la lista de palabras omitidas";
$STR_SKIPPED_PHRASE = "No se pueden buscar frases cuya primera palabra esté en la lista de palabras omitidas";
$STR_SUMMARY_NO_RESULTS_FOUND = "No hubo resultados para esta búsqueda.";
$STR_SUMMARY_FOUND_CONTAINING_ALL_TERMS = "encontrados que contienen todos los términos.";
$STR_SUMMARY_FOUND_CONTAINING_SOME_TERMS = "encontrados que contienen algún término.";
$STR_SUMMARY_FOUND = "encontrados.";
$STR_PAGES_OF_RESULTS = "páginas de resultados.";
$STR_MORETHAN = "Más de";
$STR_POSSIBLY_GET_MORE_RESULTS = "Más resultados buscando por";
$STR_ANY_OF_TERMS = "cualquiera de los términos";
$STR_ALL_CATS = "todas las categorías";
$STR_CAT_SUMMARY = "Refine su búsqueda por categoría:";
$STR_DIDYOUMEAN = "¿Quizás quiso decir:";
$STR_OR = "o";
$STR_RECOMMENDED = "Enlaces recomendados";
$STR_SORTEDBY_RELEVANCE = "Ordenados por relevancia";
$STR_SORTBY_RELEVANCE = "Ordenar por relevancia";
$STR_SORTBY_DATE = "Ordenar por fecha";
$STR_SORTEDBY_DATE = "Ordenados por fecha";
$STR_RESULT_TERMS_MATCHED = "Términos encontrados: ";
$STR_RESULT_SCORE = "Puntuación: ";
$STR_RESULT_URL = "Url:";
$STR_RESULT_PAGES = "Páginas de resultados:";
$STR_RESULT_PAGES_PREVIOUS = "Anterior";
$STR_RESULT_PAGES_NEXT = "Siguiente";
$STR_SEARCH_TOOK = "La búsqueda duró";
$STR_SECONDS = "segundos";
$STR_MAX_RESULTS = "En el caso de que obtenga demasiados resultados, Puede definir su búsqueda más aún.";
?>
