<marquee class="MarqueeNoticias" direction="up" id="marquesinaHomePage" scrollamount="2" onMouseOver="this.stop()" onMouseOut="this.start()">
<?
$arr = array(96 => "PROVINCIA ART DIJO PRESENTE EN EXPOAGRO",
						 23 => "TOPES MÁXIMOS Y MÍNIMOS",
						 95 => "PROVINCIA ART REFUERZA SU PRESENCIA EN MENDOZA",
						 94 => "EXPOAGRO 2014: PROVINCIA ART AUSPICIA EL CAMPEONATO NACIONAL DE MOTOSIERRISTAS",
						 93 => "PROVINCIA ART JUNTO A LA CULTURA EN MENDOZA",
						 92 => "PROVINCIA ART Y LA FUNDACIÓN UOCRA JUNTOS, POR LA SALUD DE LOS TRABAJADORES DE LA CONSTRUCCIÓN",
						 91 => "JORNADAS DE CAPACITACIÓN PARA LA PREVENCIÓN DE RIESGOS EN LAS LOCALIDADES COSTERAS",
						 90 => "EL BANCO DE CHUBUT Y EL GRUPO PROVINCIA AMPLÍAN SERVICIOS CONJUNTOS ",
						 89 => "JUNTO AL GOBIERNO DE MENDOZA, POR MÁS SEGURIDAD Y SALUD EN EL TRABAJO",
						 88 => "NUEVAS OFICINAS EN NEUQUÉN",
						 87 => "JUNTO A LOS MUNICIPIOS EN LA PREVENCIÓN DE ACCIDENTES",
 						 86 => "JORNADAS DE CONDUCCIÓN SEGURA",
		    		 85 => "GRAN CANTIDAD DE PARTICIPANTES EN EL STAND DE PROVINCIA",
						 84 => "PROVINCIA ART CONTINÚA PROMOVIENDO LA CULTURA DE LA PREVENCIÓN",
						 83 => "PROVINCIA ART JUNTO A LOS SECTORES PRODUCTIVOS EN CÓRDOBA",
						 82 => "PROVINCIA ART EN EL FORO NACIONAL DEL SEGURO",
						 81 => "EN PROVINCIA ART LA PROFESIONALIDAD ESTÁ GARANTIZADA",
						 80 => "PROVINCIA ART APUESTA AL FUTURO",
						 79 => "PROVINCIA ART JUNTO A ORGANIZACIONES DEL TERCER SECTOR",				 
						 78 => "PROVINCIA ART PARTICIPARÁ DEL CONGRESO REGIONAL DE SEGUROS EN MENDOZA",
						 77 => "PROVINCIA ART RECONOCIDA POR SU LABOR EN LA PREVENCIÓN DE ACCIDENTES",
						 75 => "SANTIAGO MONTOYA Y NICOLÁS SCIOLI PRESENTARON LA NUEVA IDENTIDAD",
						 74 => "PROVINCIA ART PRESENTE EN EXPOAGRO",
						 73 => "LA PROVINCIA PONE EL ACENTO EN LA PREVENCIÓN DE ACCIDENTES LABORALES",
						 72 => "COMPROMISO CON LA INCLUSIÓN LABORAL",
						 71 => "PROVINCIA ART EN EL CONGRESO REGIONAL DE SEGUROS DE SANTA FE",
						 70 => "NUEVO MARCO NORMATIVO DE RIESGOS DEL TRABAJO",
						 69 => "PROVINCIA ART SE RENUEVA EN BAHÍA BLANCA PARA SEGUIR CRECIENDO",
						 68 => "PROVINCIA ART, CON EL ÉNFASIS EN LA PREVENCIÓN",
						 67 => "NUEVO PUNTO DE ATENCIÓN EN SANTA FE",
						 66 => "PROVINCIA ART PREMIÓ EL ESFUERZO DE LAS EMPRESAS EN EL CUIDADO DE SUS TRABAJADORES",
						 64 => "APOYO AL DESARROLLO DE LOS PAS DE CUYO",
						 65 => "PROVINCIA ART EN EXPOESTRATEGAS 2012",
						 61 => "COMPROMISO CON LA PREVENCIÓN DE RIESGOS LABORALES",
						 60 => "CAPACITACIÓN ESPECIAL PARA FRIGORÍFICOS",
						 63 => "ENCUENTRO CON INTENDENTES DEL CORREDOR PRODUCTIVO",
						 62 => "PROVINCIA ART PRESENTÓ SU OFERTA DE SERVICIOS EN BARILOCHE",
						 59 => "PROVINCIA ART Y PROVINCIA SEGUROS EN EL IIIº CONGRESO FEDERAL DE SEGUROS Y RESPONSABILIDAD PROFESIONAL",
						 58 => "PROVINCIA ART IMPULSA LA IMPLEMENTACIÓN DEL TELETRABAJO",
						 57 => "PROVINCIA ART COMPROMETIDA CON LA PREVENCION DE ACCIDENTES Y RIESGOS EN EL TRABAJO",
						 55 => "PROVINCIA ART PROMUEVE EL CRECIMIENTO Y LA CAPACITACIÓN DE LOS PRODUCTORES ASESORES DE SEGUROS",
						 56 => "PROVINCIA ART PRESENTÓ SUS SERVICIOS EN EL 5º CONGRESO PROVINCIAL DE ATENCIÓN PRIMARIA DE LA SALUD Y 3º ENCUENTRO NACIONAL DE APS",
						 54 => "PROVINCIA ART ACERCA SUS HERRAMIENTAS A LA GESTIÓN PÚBLICA",
						 53 => "LOS SERVICIOS DE PROVINCIA ART, TAMBIÉN PARA EMPRESARIOS Y PRODUCTORES CORDOBESES",
						 52 => "PROVINCIA ART EN LA 9ª SEMANA ARGENTINA DE LA SALUD Y SEGURIDAD EN EL TRABAJO",
						 51 => "PROVINCIA ART OFRECE SU PROPUESTA EN MENDOZA",
						 50 => "PROVINCIA ART ACERCA SUS SERVICIOS AL AGRO",
						 49 => "NUEVO ESPACIO EN TANDIL",
						 48 => "PROVINCIA ART EN EXPOAGRO",
						 47 => "PROVINCIA ART AHORA TAMBIÉN EN MORÓN",
						 46 => "CAMBIO DE NUMERACIÓN TELEFÓNICA",
						 43 => "NUEVA OFICINA DE ATENCIÓN COMERCIAL",
						 44 => "15as. JORNADAS DE SALUD OCUPACIONAL",
						 42 => "PROVINCIA ART JUNTO A INCENTIBA",
						 41 => "PROVINCIA ART EN EXPOESTRATEGAS 2011",
						 34 => "PROVINCIA ART EN LA RURAL 2011",
						 33 => "PRESENCIA EN EXPOAGRO 2011",
						 39 => "COBERTURA DE RC PATRONAL",
						 38 => "DONACIONES PARA VILLA LA ANGOSTURA",
						 37 => "PROVINCIA ART CUMPLE 15 AÑOS",
						 36 => "NUEVA HERRAMIENTA PARA ORGANISMOS PÚBLICOS",
						 40 => "PROVINCIA ART PRESENTE EN FISA 2011",
						 35 => "DONACIONES A LA FUNDACIÓN BANCO PROVINCIA",
						 32 => "PRESENCIA INSTITUCIONAL EN LA COSTA BONAERENSE");
foreach ($arr as $key => $val) {
?>
	<div class="BoxNoticias1">
		<div class="BoxNoticias3">
			<span class="BoxNoticias2"><img src="/modules/novedades/images/mas.jpg" /></span>
			<a href="/novedades/<?= $key?>">
				<font face="Verdana" style="font-size:7pt;">
					<p style="margin-bottom:0; margin-top:0;"><?= $val?></p>
				</font>
			</a>
		</div>
	</div>
<?
}
?>
</marquee>