<table cellspacing="0" cellpadding="0">
	<tr>
		<td class="TituloSeccion">Términos y Condiciones</td>
	</tr>
	<tr>
		<td height="5"></td>
	</tr>
	<tr>
		<td class="ContenidoSeccion">
			<p>Debido a que Provincia ART S.A. recopila cierto tipo de información acerca de los usuarios de los sitios y servicios de Provincia ART S.A. y sus empresas, creemos que usted debe entender plenamente nuestra política con respecto al uso de la información que recogemos. Esta declaración sobre política de privacidad revela qué información recogemos, cómo la usamos y cómo puede corregirse o cambiarse.</p>
			<p>Al acceder al sitio de Provincia ART S.A., en la dirección <a class="linkSubrayado" href="/">www.provinciart.com.ar</a> en adelante el Sitio, y/o a cualquiera de las páginas que a través del mismo puede conocer, Usted asume el compromiso de dar acabado cumplimiento a los términos y condiciones que se indicarán a continuación. Si no es vuestra voluntad dar cumplimiento a los mismos solicitamos sírvase no acceder a este sitio.</p>
			<p>Todos los contenidos del Sitio, incluyendo pero no limitándose a, textos, gráficos, logos, imágenes, íconos y archivos, hardware y software, así como las marcas Provincia ART S.A., y <a class="linkSubrayado" href="/">www.provinciart.com.ar</a> son propiedad de Provincia ART S.A. y están protegidos por las leyes de Propiedad Intelectual. Los contenidos podrán ser utilizados como una herramienta de comunicación y/o información; cualquier otro uso, incluyendo la reproducción, modificación, distribución o transmisión sin la expresa autorización de Provincia ART S.A., queda estrictamente prohibida.</p>
			<p>Ponemos en su conocimiento que la información suministrada al ingresar a este Sitio es de exclusiva responsabilidad de las empresas que proveen la misma, siendo Provincia ART S.A. ajeno a cualquier responsabilidad que sobre la misma pudiera corresponder.</p>
			<p>Provincia ART S.A. no es responsable por la veracidad y exactitud de la información que en este sitio se provea, ni de los cambios que sobre la misma pudieran acontecer.
			<p>El acceso a otras páginas a través de este sitio no importará para Provincia ART S.A. obligación alguna respecto de la información que en estas otras páginas pudieran describirse, siendo esta responsabilidad única y excluyente de las empresas y/u organismos que la provean.</p>
			<p>Los servicios y/o productos que pueden conocerse a través de este Sitio o de las páginas a las que se pueda acceder a través del mismo, reunirán las condiciones que cada empresa y/u organismo determine reservándose éstas el derecho de cancelar, modificar, limitar, etc, la provisión de los mismos, no generando esto responsabilidad alguna para Provincia ART S.A.</p>
			<p>Las marcas y/o logos que se encuentren en este Sitio son de única propiedad de las personas físicas y/o jurídicas que a su nombre las hubieran registrado.</p>
			<p>Provincia ART S.A. no se responsabiliza por los errores u omisiones sobre la información brindada mediante el acceso a este Sitio, o a los demás sitios a los que a través del mismo se pudiera obtener. Los productos, bienes y/o servicios se proveerán en las zonas que las empresas y/u organismos determinen y bajo las condiciones que éstas impongan.</p>
			<p>Provincia ART S.A. no es responsable de las fallas o defectos que pudieran presentar los productos, bienes y/o servicios de los que se tenga conocimiento mediante el acceso a este sitio o las páginas a las que se acceda a través de él, ni de los gastos directos y/o indirectos que éstos provoquen.</p>
			<p>Provincia ART S.A. no se responsabiliza por las demoras, interrupciones y defectos que pudieran existir en las transmisiones, así como tampoco de los virus o fallas del sistema o línea.</p>
			<p>En relación a los productos, bienes y/o servicios de propiedad de Provincia ART S.A. que pudieran ser ofrecidos en esta página o la información que a través de ella se pudiera obtener, Provincia ART S.A. se reserva el derecho de suprimir, cancelar y/o modificar de cualquier modo los datos o características de ellos no generando esto responsabilidad alguna para Provincia ART S.A.</p>
			<p>Será facultativo para Provincia ART S.A. el otorgamiento de cada uno de los bienes, productos y servicios que pudieran ofrecerse en esta página, encontrándose sujeta su aprobación al cumplimiento de las condiciones que la entidad ó sus empresas vinculadas establezcan al efecto en cada caso.</p>
			<p>La información, bienes, productos y/o servicios que se ofrezcan en esta página están sujetos a cambios, no garantizándose que tal información, bienes, productos y/o servicios ofrecidos se encuentren disponibles en todas las áreas geográficas del país y/o del exterior.</p>
			<p>Los productos, bienes y/o servicios ofrecidos no se encuentran garantizados por Provincia ART S.A. ni por otras entidades, no siendo responsabilidad de esta compañía cualquier pérdida que pudiera sufrirse en relación a las inversiones y/o contrataciones formalizadas que pudiera suscitarse en función de las variaciones propias del mercado.</p>
			<p>Los bienes, productos y/o servicios que se encuentren en este sitio serán contratados de acuerdo a las modalidades y características que Provincia ART S.A. establezca, no siendo ésta responsable de los errores u omisiones en la información brindada sobre los mismos.</p>
			<p>Lo contenido en el presente es a los únicos efectos informativos, los datos que se presentan no son y no han intentado ser una oferta de compra o suscripción, ni una invitación a ofrecer en venta o rescate, ni una solicitud de compra de ninguno de los instrumentos financieros mencionados, ni la confirmación de ninguna transacción, no pudiendo ser interpretada como tales excepto que expresamente se indicare lo contrario. Cualquier decisión de compra, suscripción, constitución o venta, rescate de cualquier instrumento debe estar basada en información públicamente disponible teniendo en cuenta, cuando así fuere conveniente, el prospecto de emisión, reglamento de gestión y/o cualquier otra información provista por el emisor o la entidad reguladora del mercado donde cotice. A pesar de que la información contenida en el presente ha sido obtenida de fuentes confiables, los precios de mercado, datos, u otra información incluida en este documento no están ni pueden ser considerados como completos ni inalterables, pudiendo estar sujetos a cambios sin ningún tipo de noticia previa. Todas las opiniones y/o estimaciones incluidas en el presente constituyen nuestra opinión a la fecha de emisión estando sujetas a cambios que no han de ser previamente notificados.</p>
		</td>
	</tr>
</table>