<table cellspacing="0" cellpadding="0">
	<tr>
		<td class="TituloSeccion">Política de Privacidad</td>
	</tr>
	<tr>
		<td height="5"></td>
	</tr>
	<tr>
		<td class="ContenidoSeccion">
			<p>Declaración sobre la política de Provincia ART S.A. referente a privacidad de los datos incorporados al Sitio.</p>
			<p>Declaración General Debido a que Provincia ART S.A. recopila cierto tipo de información acerca de los usuarios de los sitios y servicios de Provincia ART S.A., creemos que usted debe entender plenamente nuestra política con respecto al uso de la información que recogemos. Esta declaración sobre política de privacidad revela qué información recogemos, cómo la usamos y cómo puede corregirse o cambiarse.</p>
			<p><b>1. ¿Qué información recopilamos?</b></p>
			<p>Cierta información se obtendrá de los datos suministrados por el usuario cuando se registre en el Sitio, como ser, nombre, domicilio, dirección electrónica, nacionalidad, edad, sexo. Los fines de Provincia ART S.A. al recoger información personal pueden incluir ofertas de servicios al cliente, manejo de la red, encuestas entre clientes, subscripciones, ofertas de servicios relacionados, facturación y otros intercambios de información en su Sitio. Provincia ART S.A. no revelará ni compartirá esta información que puede identificar a las personas con ninguna otra empresa u organización sin el consentimiento informado del consumidor que proporciona dicha información (excepto cuando así lo requiera la ley o a solicitud del gobierno); tal consentimiento podría ser ofrecido al elegir la opción de recopilar información descrita en el punto 5, abajo. Los datos agregados permiten a Provincia ART S.A. analizar el tráfico del sitio y manejar su relación con sus productos. De esta manera, les proporcionamos a nuestros usuarios un servicio más personalizado.</p>
			<p><b>2. ¿Qué hace Provincia ART S.A. con la información que recoge?</b></p>
			<p>Provincia ART S.A. utiliza la información de contacto de los usuarios para enviar información sobre nuestra empresa. Los usuarios pueden optar por no recibir envíos en el futuro; véase el punto 5 abajo para elegir si desean recibir o no dicha información. Provincia ART S.A. puede usar la información personal para determinar los datos demográficos de nuestros usuarios y distribuir información estadística y general del mercado. Estos datos demográficos siempre representan información agregada y nunca identifican a un usuario específico. La información personal que usted le suministró a Provincia ART S.A. no será revelada a nadie fuera de Provincia ART S.A. Provincia ART S.A. puede utilizar su dirección IP para ayudar a diagnosticar problemas con nuestro servidor y administrar nuestra página Web.</p>
			<p><b>3. ¿Qué es una cookie?</b></p>
			<p>Una cookie es un pequeño archivo de datos que algunos sitios Web escriben en su disco duro cuando usted los visita. Un archivo cookie puede contener tal información como la identificación del usuario que el sitio utiliza para rastrear las páginas que usted ha visitado. Pero la única información personal que un cookie puede contener es información que usted mismo suministra. Una cookie no puede leer datos de su disco duro ni leer los archivos cookie creados por otros sitios. El Sitio de Provincia ART S.A. actualmente no utiliza cookies para rastrear los patrones de tráfico del usuario de vez en cuando. El Sitio de Provincia ART S.A. podría contener enlaces con otros sitios. Provincia ART S.A. advierte que al no ser titular de la información contenida en, u obtenida a través de, estos vínculos, no es responsable de la veracidad de los mismos ni de la política de privacidad de dichos sitios. Tenga en cuenta que las salas de conversación, foros, tableros de mensajes y/o grupos noticiosos de otros sitios, a los cuales se pudiera acceder a través del Sitio de Provincia ART S.A., tampoco resultan servicios prestados por Provincia ART S.A. y que no tenemos control sobre los contenidos o la información brindada por éstos. Recuerde que cualquier información que se revele en estas áreas pasa a ser de dominio público y es usted quien debe tomar precauciones al decidir si desea revelar información personal.</p>
			<p><b>4. ¿Con quién se comparte la información?</b></p>
			<p>No compartimos información sobre usuarios individuales con ningún tercero u otras empresas. Pero según mencionamos anteriormente, podemos compartir información estadística agregada sobre el uso del Sitio o los servicios de Provincia ART S.A. para adaptar mejor nuestro contenido a las necesidades de los usuarios y clientes, de acuerdo a los datos demográficos recopilados.</p>
			<p><b>5. Opciones del usuario de recibir o no recibir información</b></p>
			<p>Si por cualquier motivo Provincia ART S.A. decide recoger y utilizar información que identifica a las personas para cualquier fin que no se haya enumerado anteriormente, Provincia ART S.A. informará a los usuarios sobre el uso de información que puede identificar a las personas individualmente No obstante cualquier otra provisión en esta declaración al contrario, Provincia ART S.A. tendrá el derecho de divulgar cierta información privada si es requerido por leyes generales o las autoridades regulatorias o legales, para proteger nuestros derechos y/o intereses. Provincia ART S.A. tiene la capacidad de recoger información sobre los usuarios relacionada con sus intereses y hábitos de compra. A fin de servirle mejor y ajustar la experiencia de Provincia ART S.A. a sus necesidades y gustos específicos, Provincia ART S.A. le podrá ofrecer a usted la opción de recibir información de terceros sobre temas, productos y servicios que sean de interés para usted. Según se mencionó anteriormente, Provincia ART S.A. puede usar la información de contacto del usuario para enviarle información al usuario sobre nuestra empresa. Los usuarios pueden elegir no recibir envíos futuros, modificando esta opción donde se indique o mandando un mensaje por correo electrónico con su nombre a <a class="linkSubrayado" href="mailto:info@provart.com.ar">info@provart.com.ar</a>.</p>
			<p><b>6. Opciones del usuario de modificar la información suministrada.</b></p>
			<p>El Sitio de Provincia ART S.A. ofrece a los usuarios la capacidad de corregir o cambiar la información recogida durante la registración (véase el punto 5 arriba). Las instrucciones para hacerlo se pueden encontrar en nuestra área de actualización de datos. Los usuarios pueden cambiar esta información en cualquier momento y tan a menudo como sea necesario. Los usuarios que experimenten problemas o que tengan preguntas sobre la manera en que nuestros servicios funcionan pueden comunicarse con nosotros a <a class="linkSubrayado" href="mailto:info@provart.com.ar">info@provart.com.ar</a>.</p>
			<p><b>7. Procedimientos de seguridad.</b></p>
			<p>Cuando se trata de información que a criterio de Provincia ART S.A. haya que proteger, el Sitio opera con sistemas de protección estándar de la industria y de protección de contraseñas. La información pública no se encuentra protegida.</p>
			<p><b>8. Cambios en la política de Provincia ART S.A. referente a privacidad.</b></p>
			<p>Si decidimos cambiar nuestra política sobre privacidad para el Sitio <a class="linkSubrayado" href="/" target="_blank">www.provinciart.com.ar</a> anunciaremos aquí dichos cambios, de manera que usted siempre pueda saber qué información recogemos, cómo podríamos usar dicha información y si la revelaremos a alguien.</p>
		</td>
	</tr>
</table>